export declare const FUSO_HORARIO: "America/Bahia";
export declare const PERFIS: readonly ["SOCIO", "GESTORA", "ASSESSORA_JR", "ESTAGIARIO"];
export type Perfil = (typeof PERFIS)[number];
export declare const HIERARQUIA_PERFIL: Record<Perfil, number>;
export declare const STATUS_USUARIO: readonly ["ATIVO", "INATIVO", "FERIAS", "AFASTADO"];
export type StatusUsuario = (typeof STATUS_USUARIO)[number];
export declare const TIPOS_PONTO: readonly ["ENTRADA", "SAIDA_ALMOCO", "RETORNO_ALMOCO", "SAIDA_FINAL"];
export type TipoPonto = (typeof TIPOS_PONTO)[number];
export declare const SEQUENCIA_PONTO_OBRIGATORIA: readonly TipoPonto[];
export declare const REGIMES_PONTO: readonly ["PRESENCIAL", "HOME_OFFICE"];
export type RegimePonto = (typeof REGIMES_PONTO)[number];
export declare const PONTO_FOTO_MAX_BYTES: number;
export declare const PONTO_JUSTIFICATIVA_MIN = 30;
export declare const RELATORIO_MIN_CARACTERES: {
    readonly atividades: 100;
    readonly dificuldades: 50;
    readonly justificativa: 50;
};
export declare const TIPOS_ATESTADO: readonly ["MEDICO", "FACULDADE", "OUTRO"];
export type TipoAtestado = (typeof TIPOS_ATESTADO)[number];
export declare const PRIORIDADES_DEMANDA: readonly ["BAIXA", "MEDIA", "ALTA", "URGENTE"];
export type PrioridadeDemanda = (typeof PRIORIDADES_DEMANDA)[number];
export declare const STATUS_DEMANDA: readonly ["PENDENTE", "ANDAMENTO", "ENTREGUE", "EM_CORRECAO", "CONCLUIDA", "VENCIDA"];
export type StatusDemanda = (typeof STATUS_DEMANDA)[number];
export declare const TIPOS_DEMANDA: readonly ["JURIDICA", "ADMINISTRATIVA", "PESQUISA", "ATENDIMENTO", "OUTRO"];
export type TipoDemanda = (typeof TIPOS_DEMANDA)[number];
export declare const NOTAS_CORRECAO: readonly [0, 8, 10];
export type NotaCorrecao = (typeof NOTAS_CORRECAO)[number];
export declare const CATEGORIAS_CHECKLIST: readonly ["S1_SEIRI", "S2_SEITON", "S3_SEISO", "S4_SEIKETSU", "S5_SHITSUKE", "ROTINA_INICIO", "ROTINA_JURIDICA", "ROTINA_ADMIN", "ENCERRAMENTO"];
export type CategoriaChecklist = (typeof CATEGORIAS_CHECKLIST)[number];
export declare const PERFIS_CHECKLIST: readonly ["TODOS", "ESTAGIARIO", "ASSESSORA_JR"];
export type PerfilChecklist = (typeof PERFIS_CHECKLIST)[number];
export declare const TIPOS_CERTIFICADO: readonly ["SEMANAL", "MENSAL", "ANUAL", "DESTAQUE"];
export type TipoCertificado = (typeof TIPOS_CERTIFICADO)[number];
export declare const TIPOS_NOTIFICACAO: readonly ["LEMBRETE_PONTO", "ALERTA_PRAZO", "DEMANDA_ATRIBUIDA", "DEMANDA_CORRIGIDA", "AUSENCIA_PONTO", "CERTIFICADO", "RELATORIO_RECEBIDO", "AUSENCIA_RELATORIO", "OUTRO"];
export type TipoNotificacao = (typeof TIPOS_NOTIFICACAO)[number];
export declare const PONTOS_MAXIMOS_SEMANA: {
    readonly pontualidade: 25;
    readonly qualidade: 40;
    readonly extras: 15;
    readonly checklist: 10;
    readonly relatorios: 10;
};
export declare const PONTOS_MAXIMOS_TOTAL = 100;
export declare const SENHA_MIN_CARACTERES = 8;
export declare const SENHA_DIAS_EXPIRACAO = 90;
export declare const SENHA_HISTORICO_BLOQUEADO = 5;
export declare const UPLOAD_MIMES_ATESTADO: readonly ["application/pdf", "image/jpeg", "image/png"];
export declare const ACAO_AUDITORIA: {
    readonly LOGIN: "LOGIN";
    readonly LOGIN_FALHA: "LOGIN_FALHA";
    readonly LOGOUT: "LOGOUT";
    readonly CRIAR_USUARIO: "CRIAR_USUARIO";
    readonly EDITAR_USUARIO: "EDITAR_USUARIO";
    readonly REMOVER_USUARIO: "REMOVER_USUARIO";
    readonly REDEFINIR_SENHA: "REDEFINIR_SENHA";
    readonly ACEITAR_POP: "ACEITAR_POP";
    readonly REGISTRAR_PONTO: "REGISTRAR_PONTO";
    readonly EDITAR_PONTO: "EDITAR_PONTO";
    readonly ENVIAR_RELATORIO: "ENVIAR_RELATORIO";
    readonly CRIAR_DEMANDA: "CRIAR_DEMANDA";
    readonly DELEGAR_DEMANDA: "DELEGAR_DEMANDA";
    readonly CORRIGIR_DEMANDA: "CORRIGIR_DEMANDA";
    readonly EMITIR_CERTIFICADO: "EMITIR_CERTIFICADO";
    readonly CRIAR_CHECKLIST_ITEM: "CRIAR_CHECKLIST_ITEM";
    readonly ATUALIZAR_CHECKLIST_ITEM: "ATUALIZAR_CHECKLIST_ITEM";
    readonly INATIVAR_CHECKLIST_ITEM: "INATIVAR_CHECKLIST_ITEM";
};
export type AcaoAuditoria = (typeof ACAO_AUDITORIA)[keyof typeof ACAO_AUDITORIA];
export declare function podeDelegarPara(delegador: Perfil, destino: Perfil): boolean;
export declare function nivelPerfil(perfil: Perfil): number;
//# sourceMappingURL=index.d.ts.map